openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /building_usage:
    get:
      operationId: building_usage_retrieve
      description: Retrieve the usage label of the specified building
      parameters:
      - in: query
        name: building_id
        schema:
          type: integer
        description: Building id for which retrieve usage label
        required: true
      tags:
      - building_usage
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
          description: ''
  /carbon_impact:
    get:
      operationId: carbon_impact_retrieve
      description: Compute and return the total carbon impact of the specified building
      parameters:
      - in: query
        name: building_id
        schema:
          type: integer
        description: Building id for which compute carbon impact
        required: true
      tags:
      - carbon_impact
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: number
                format: double
          description: ''
  /total_surface:
    get:
      operationId: total_surface_retrieve
      description: Compute and return the surface of the specified building
      parameters:
      - in: query
        name: building_id
        schema:
          type: integer
        description: Building id for which compute surface
        required: true
      tags:
      - total_surface
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: integer
          description: ''
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
